const departments = [
  {
    name: "Áudio Profissional",
    link: "/audio-profissional",
    items: [
      { title: "Acessórios", link: "/audio-profissional/acessorios" },
      { title: "Alto Falantes", link: "/audio-profissional/alto-falantes" },
      { title: "Amplificadores", link: "/audio-profissional/amplificadores" },
      {
        title: "Caixas Acústicas",
        link: "/audio-profissional/caixas-acusticas",
      },
      { title: "Direct box DI", link: "/audio-profissional/direct-box-di" },
      { title: "Energia", link: "/audio-profissional/energia" },
      { title: "Equipamentos DJ", link: "/audio-profissional/equipamentos-dj" },
      { title: "Fones de ouvido", link: "/audio-profissional/fones-de-ouvido" },
      { title: "Mesas de som", link: "/audio-profissional/mesas-de-som" },
      { title: "Microfones", link: "/audio-profissional/microfones" },
      {
        title: "Monitores sem fio",
        link: "/audio-profissional/monitores-sem-fio",
      },
      { title: "Phantom power", link: "/audio-profissional/phantom-power" },
      {
        title: "Processadores de sinal",
        link: "/audio-profissional/processadores-de-sinal",
      },
    ],
  },
  {
    name: "Cordas",
    link: "/cordas",
    items: [
      { title: "Acessórios", link: "/cordas/acessorios" },
      { title: "Amplificadores", link: "/cordas/amplificadores" },
      { title: "Baixolões", link: "/cordas/baixoloes" },
      { title: "Bandolins", link: "/cordas/bandolins" },
      { title: "Banjos", link: "/cordas/banjos" },
      { title: "Cavaquinhos", link: "/cordas/cavaquinhos" },
      { title: "Contrabaixos", link: "/cordas/contrabaixos" },
      { title: "Guitarras", link: "/cordas/guitarras" },
      { title: "Interfaces", link: "/cordas/interfaces" },
      { title: "Pedais", link: "/cordas/pedais" },
      { title: "Pedaleiras", link: "/cordas/pedaleiras" },
      { title: "Ukuleles", link: "/cordas/ukuleles" },
      { title: "Viola de arco", link: "/cordas/violas-de-arco" },
      { title: "Violas", link: "/cordas/violas" },
      { title: "Violinos", link: "/cordas/violinos" },
      { title: "Violões", link: "/cordas/violoes" },
      { title: "Violoncelos", link: "/cordas/violoncelos" },
    ],
  },
  {
    name: "Estúdio",
    link: "/estudio",
    items: [
      { title: "Acessórios", link: "/estudio/acessorios" },
      { title: "Controladores", link: "/estudio/controladores" },
      { title: "Conversores de áudio", link: "/estudio/conversores-de-audio" },
      { title: "Fones de ouvido", link: "/estudio/fones-de-ouvido" },
      { title: "Gravadores", link: "/estudio/gravadores" },
      { title: "Interfaces de áudio", link: "/estudio/interfaces-de-audio" },
      { title: "Mesas de som", link: "/estudio/mesas-de-som" },
      { title: "Microfones", link: "/estudio/microfones" },
      { title: "Mixers de vídeos", link: "/estudio/mixers-de-videos" },
      { title: "Monitores", link: "/estudio/monitores-de-audio" },
      { title: "Pré amplificadores", link: "/estudio/pre-amplificadores" },
      { title: "Softwares e plugins", link: "/estudio/softwares-e-plugins" },
      { title: "Subwoofers", link: "/estudio/subwoofers" },
      { title: "Vara de boom", link: "/estudio/vara-de-boom" },
    ],
  },
  {
    name: "Home Theater",
    link: "/home-theater",
    items: [
      { title: "Acessórios", link: "/home-theater/acessorios" },
      { title: "Amplificadores", link: "/home-theater/amplificadores" },
      { title: "Blue ray / DVD", link: "/home-theater/blue-ray-dvd" },
      { title: "Caixas Acústicas", link: "/home-theater/caixas-acusticas" },
      { title: "Energia", link: "/home-theater/energia" },
      { title: "Lift", link: "/home-theater/lift" },
      { title: "Projetores", link: "/home-theater/projetores" },
      { title: "Receivers", link: "/home-theater/receivers" },
      { title: "Setorizadores", link: "/home-theater/setorizadores" },
      {
        title: "Sistema de Home Theater",
        link: "/home-theater/conjunto--home-theater",
      },
      { title: "Som portátil", link: "/home-theater/som-portatil" },
      { title: "Soundbar", link: "/home-theater/soundbar" },
      { title: "Telas de projeção", link: "/home-theater/telas-de-projecao" },
      { title: "Toca discos", link: "/home-theater/toca-discos" },
    ],
  },
  {
    name: "Percussão",
    link: "/percussao",
    items: [
      { title: "Acessórios", link: "/percussao/acessorios" },
      { title: "Afuchê", link: "/percussao/afuche" },
      { title: "Agogo", link: "/percussao/agogo" },
      { title: "Atabaque", link: "/percussao/atabaque" },
      { title: "Baterias", link: "/percussao/baterias" },
      { title: "Bateron", link: "/percussao/bateron" },
      { title: "Bloco Sonoro", link: "/percussao/bloco-sonoro" },
      { title: "Bongo", link: "/percussao/bongo" },
      { title: "Cajon", link: "/percussao/cajon" },
      { title: "Carrilhão", link: "/percussao/carrilhao" },
      { title: "Caxixi", link: "/percussao/caxixi" },
      { title: "Conga", link: "/percussao/conga" },
      { title: "Cowbell", link: "/percussao/cowbell" },
      { title: "Cuica", link: "/percussao/cuica" },
      { title: "Djembe", link: "/percussao/djembe" },
      { title: "Ganza", link: "/percussao/ganza" },
      { title: "Malacacheta", link: "/percussao/malacacheta" },
      { title: "Maracas", link: "/percussao/maracas" },
      { title: "Módulo", link: "/percussao/modulo" },
      { title: "Ovinho", link: "/percussao/ovinho" },
      { title: "Pandeiro", link: "/percussao/pandeiro" },
      { title: "Queixada", link: "/percussao/queixada" },
      { title: "Rebolo", link: "/percussao/rebolo" },
      { title: "Reco reco", link: "/percussao/reco--reco" },
      { title: "Repinique", link: "/percussao/repinique" },
      { title: "Repique", link: "/percussao/repique" },
      { title: "Surdo", link: "/percussao/surdo" },
      { title: "Tamborim", link: "/percussao/tamborim" },
      { title: "Tantam", link: "/percussao/tantam" },
      { title: "Tarol", link: "/percussao/tarol" },
      { title: "Timba", link: "/percussao/timba" },
      { title: "Timbal", link: "/percussao/timbal" },
      { title: "Timbales", link: "/percussao/timbales" },
      { title: "Triângulo", link: "/percussao/triangulo" },
      { title: "Washboard", link: "/percussao/washboard" },
      { title: "Zabumba", link: "/percussao/zabumba" },
    ],
  },
  {
    name: "Som Ambiente",
    link: "/som-ambiente",
    items: [
      { title: "Alto falantes", link: "/audio-profissional/alto-falantes" },
      { title: "Amplificadores", link: "/som-ambiente/amplificadores" },
      { title: "Base de microfones", link: "/som-ambiente/bases-de-microfones" },
      { title: "Cabos", link: "/som-ambiente/cabos-de-audio" },
      { title: "Caixas Acústicas", link: "/som-ambiente/caixas-acusticas" },
      { title: "Cornetas", link: "/som-ambiente/cornetas" },
      { title: "Megafones", link: "/som-ambiente/megafones" },
      { title: "Microfones", link: "/som-ambiente/microfones" },
      { title: "Potenciômetros", link: "/som-ambiente/potenciometros" },
      { title: "Pré-amplificadores", link: "/som-ambiente/pre-amplificadores" },
      { title: "Seletores", link: "/som-ambiente/seletores" },
      { title: "Suportes", link: "/som-ambiente/suportes" },
      { title: "Transformadores", link: "/som-ambiente/transformadores" },
    ],
  },
  {
    name: "Sopro",
    link: "/sopro",
    items: [
      { title: "Acessórios", link: "/sopro/acessorios" },
      { title: "Bombardinos", link: "/sopro/bombardinos" },
      { title: "Clarinetas", link: "/sopro/clarinetas" },
      { title: "Escaletas", link: "/sopro/escaletas" },
      { title: "Flautas", link: "/sopro/flautas" },
      { title: "Gaitas", link: "/sopro/gaitas" },
      { title: "Kazoos", link: "/sopro/kazoos" },
      { title: "Saxofones", link: "/sopro/saxofones" },
      { title: "Trombones", link: "/sopro/trombones" },
      { title: "Trompetes", link: "/sopro/trompetes" },
    ],
  },
  {
    name: "Teclas",
    link: "/teclas",
    items: [
      { title: "Acessórios", link: "/teclas/acessorios" },
      { title: "Acordeons", link: "/teclas/acordeons" },
      { title: "Amplificadores", link: "/teclas/amplificadores" },
      { title: "Controladores", link: "/teclas/controladores" },
      { title: "Pianos", link: "/teclas/pianos" },
      { title: "Sintetizadores", link: "/teclas/sintetizadores" },
      { title: "Teclados", link: "/teclas/teclado-musical" },
    ],
  },
];

export default departments;
